fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    dirtree: "https://github.com/AlexCline/puppet-dirtree"
    apache: "https://github.com/puppetlabs/puppetlabs-apache"
    wget: "https://github.com/maestrodev/puppet-wget"
  symlinks:
    moodle: "#{source_dir}"
