---
language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.3.1
    env: Puppet_GEM_VERSION="~> 4.0"
notifications:
  email: false
sudo: false
script:
  - "rake lint"
  - "rake validate"
  - "rake spec SPEC_OPTS='--format documentation'"
install:
  - bundle install
  - rspec-puppet-init
cache: bundler
